version: '3.4'
services:
  cart-share:
    image: alfresco-share-cart:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../cart-share-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: cart-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
  cart-acs:
    image: alfresco-content-services-cart:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../cart-platform-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    command: ["catalina.sh", "run"]
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - cart-acs-volume:/usr/local/tomcat/alf_data
      - ../../../cart-platform/target/classes:/usr/local/tomcat/hotswap-agent/sample-project-platform/target/classes
      - ../../../cart-integration-tests/target/test-classes:/usr/local/tomcat/hotswap-agent/sample-project-integration-tests/target/test-classes
    depends_on:
      - cart-postgres
  cart-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - cart-db-volume:/var/lib/postgresql/data
  cart-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: cart-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: cart-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - cart-ass-volume:/opt/alfresco-search-services/contentstore
      - cart-ass-volume:/opt/alfresco-search-services/data
volumes:
  cart-acs-volume:
    external: true
  cart-db-volume:
    external: true
  cart-ass-volume:
    external: true
